# ========================================
# Work & Hunger Configuration
# ========================================
# This file controls villager work-related hunger mechanics
# Separated from main config for better organization

# Main work-hunger settings
enabled: true
hunger-decrease-per-work: 1
request-food-threshold: 15
min-hunger-to-work: 5          # Villagers won't work if hunger is below this level
nearby-villager-range: 40.0
max-food-level: 16             # Maximum food level villagers will try to eat up to (vanilla Minecraft default: 20)

# When to check hunger and request food
check-triggers:
  periodic-check:
    enabled: true          # Scheduled background checks
    interval-seconds: 30   # Every 5 minutes

# Villager request system settings
villager-requests:
  enabled: true
  min-keep-food: 3         # Minimum food items to keep before sharing
  generosity-factor: 0.6   # Percentage of excess items to share (60%)
  
  # Physical interaction mode (walking and dropping items)
  physical-interaction:
    enabled: true                    # Villagers walk to each other and drop items
    max-delivery-distance: 32.0     # Max distance for physical delivery
    item-claim-duration: 30         # How long items stay marked (seconds)
    delivery-walk-speed: 1.0        # Walk speed multiplier during delivery

# Equipment request system (villagers sharing combat gear during alerts)
equipment-requests:
  enabled: true                     # Enable equipment sharing during alerts
  request-range: 32.0              # Distance to search for equipment providers
  max-delivery-time-minutes: 5     # Maximum time before delivery is considered failed
  
  # Equipment priority order (higher values = higher priority)
  # Villagers will prioritize requesting and delivering higher priority items first
  priority-order:
    NETHERITE_SWORD: 100
    DIAMOND_SWORD: 95
    IRON_SWORD: 90
    STONE_SWORD: 85
    WOODEN_SWORD: 80
    BOW: 75
    CROSSBOW: 70
    TRIDENT: 65
    NETHERITE_HELMET: 60
    DIAMOND_HELMET: 55
    IRON_HELMET: 50
    CHAINMAIL_HELMET: 45
    LEATHER_HELMET: 40
    NETHERITE_CHESTPLATE: 59
    DIAMOND_CHESTPLATE: 54
    IRON_CHESTPLATE: 49
    CHAINMAIL_CHESTPLATE: 44
    LEATHER_CHESTPLATE: 39
    NETHERITE_LEGGINGS: 58
    DIAMOND_LEGGINGS: 53
    IRON_LEGGINGS: 48
    CHAINMAIL_LEGGINGS: 43
    LEATHER_LEGGINGS: 38
    NETHERITE_BOOTS: 57
    DIAMOND_BOOTS: 52
    IRON_BOOTS: 47
    CHAINMAIL_BOOTS: 42
    LEATHER_BOOTS: 37
    SHIELD: 30
  
  # Sharing rules for equipment
  sharing-rules:
    min-keep-weapons: 1            # Always keep at least 1 weapon
    min-keep-armor-pieces: 1       # Can give away all armor pieces if needed
    allow-sharing-equipped: false   # Don't share currently equipped items
    share-better-than-equipped: true # Share inventory items if equipped item is better

# Work-based item generation (instead of vanilla trade restocking)
work-item-generation:
  enabled: true              # Enable work-based item generation
  disable-vanilla-restock: true  # Disable vanilla trade restocking when enabled
  
  # Smart generation settings
  check-actual-trades: true   # Only generate items that exist in villager's current trades
                             # This prevents generating diamond tools if villager doesn't trade them

# Realistic trade inventory exchanges
realistic-trade-inventory:
  enabled: true              # Enable realistic trade inventory exchanges
                               # When enabled, villagers lose emeralds they pay and gain items players sell
  
  # Profession-specific finished products generated when working
  # Format: "ITEM_NAME:quantity_per_work:max_limit" - one random item per work cycle
  # Empty arrays [] = profession can naturally generate their own trade items (no help needed)
  profession-items:
    ARMORER:
      - "EMERALD:2:64"            # Generate 2 emeralds, max 64 total
      - "IRON_HELMET:1:4"         # Generate 1 helmet, max 4 total
      - "IRON_CHESTPLATE:1:4" 
      - "IRON_LEGGINGS:1:4"
      - "IRON_BOOTS:1:4"
      - "CHAINMAIL_HELMET:1:2"
      - "CHAINMAIL_CHESTPLATE:1:2"
      - "CHAINMAIL_LEGGINGS:1:2" 
      - "CHAINMAIL_BOOTS:1:2"
      - "DIAMOND_HELMET:1:2"      # Covers enchanted diamond helmet trades
      - "DIAMOND_CHESTPLATE:1:2"  # Covers enchanted diamond chestplate trades
      - "DIAMOND_LEGGINGS:1:2"    # Covers enchanted diamond leggings trades
      - "DIAMOND_BOOTS:1:2"       # Covers enchanted diamond boots trades
      - "SHIELD:1:3"
      - "BELL:1:2"
    BUTCHER:
      - "EMERALD:2:64"
      - "RABBIT_STEW:1:5"
      - "COOKED_PORKCHOP:3:15"
      - "COOKED_CHICKEN:3:15"
    CARTOGRAPHER:
      - "EMERALD:2:64"
      - "MAP:1:8"
      - "ITEM_FRAME:2:10"
      - "WHITE_BANNER:1:5"
    CLERIC:
      - "EMERALD:2:64"
      - "REDSTONE:4:32"
      - "LAPIS_LAZULI:3:24"
      - "GLOWSTONE:2:16"
    FARMER:
      - "EMERALD:2:64"# Can farm/cook naturally
    FISHERMAN:
      - "EMERALD:2:64"# Can fish/cook naturally
    FLETCHER:
      - "EMERALD:2:64"
      - "ARROW:16:128"            # Generate 16, max 128 total
      - "BOW:1:3"                 # Covers enchanted bow trades
      - "CROSSBOW:1:3"            # Covers enchanted crossbow trades
      - "TIPPED_ARROW:5:40"       # Tipped arrows with effects
    LEATHERWORKER:
      - "EMERALD:2:64"
      - "LEATHER_HELMET:1:4"
      - "LEATHER_CHESTPLATE:1:4"
      - "LEATHER_LEGGINGS:1:4"
      - "LEATHER_BOOTS:1:4"
      - "LEATHER_HORSE_ARMOR:1:2"
      - "SADDLE:1:2"
    LIBRARIAN:
      - "EMERALD:2:64"
      - "ENCHANTED_BOOK:1:5"      # Main librarian trade - covers all enchanted books
      - "BOOKSHELF:1:8"
      - "LANTERN:1:6"
      - "CLOCK:1:3"
      - "COMPASS:1:3" 
      - "NAME_TAG:1:5"
    MASON:
      - "EMERALD:2:64"
      - "BRICK:10:80"
      - "CHISELED_STONE_BRICKS:4:32"
      - "POLISHED_ANDESITE:4:32"
      - "POLISHED_GRANITE:4:32"
      - "POLISHED_DIORITE:4:32"
      - "TERRACOTTA:8:64"
    SHEPHERD:
      - "EMERALD:2:64"
      - "WHITE_WOOL:3:24"
      - "BLACK_WOOL:3:24"
      - "GRAY_WOOL:3:24"
      - "LIGHT_GRAY_WOOL:3:24"
      - "BROWN_WOOL:3:24"
    TOOLSMITH:
      - "EMERALD:2:64"
      - "STONE_AXE:1:3"
      - "STONE_SHOVEL:1:3" 
      - "STONE_PICKAXE:1:3"
      - "STONE_HOE:1:3"
      - "IRON_AXE:1:3"
      - "IRON_SHOVEL:1:3"
      - "IRON_PICKAXE:1:3"
      - "IRON_HOE:1:3"
      - "DIAMOND_AXE:1:2"         # Covers enchanted diamond axe trades
      - "DIAMOND_SHOVEL:1:2"      # Covers enchanted diamond shovel trades
      - "DIAMOND_PICKAXE:1:2"     # Covers enchanted diamond pickaxe trades
      - "DIAMOND_HOE:1:2"         # Covers enchanted diamond hoe trades
    WEAPONSMITH:
      - "EMERALD:2:64"
      - "IRON_AXE:1:3"
      - "IRON_SWORD:1:3"
      - "DIAMOND_SWORD:1:2"       # Covers enchanted diamond sword trades
      - "DIAMOND_AXE:1:2"         # Covers enchanted diamond axe trades
      - "BELL:1:2"

# Anti-enslavement protection (villagers refuse to work when confined)
anti-enslavement:
  enabled: true                    # Enable anti-enslavement protection
  minimum-walkable-area: 25        # Minimum walkable blocks needed for villagers to work (5x5 area)
  max-area-scan: 500              # Maximum blocks to scan (performance limit)

# Configuration version (do not change)
config-version: 1